# Generated by Django 5.1.1 on 2024-10-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='proveedor_images/'),
        ),
    ]
